---
title: "Tooltip"
description: "Quarto에서 tooltip 구현 검토한 것을 정리하였습니다."
author: "BenKorea"
date: "2024-12-08"
date-modified: "2024-12-08"
categories: [Quarto, Tools, Tooltip]
---

## Pandoc markdown

-   Quarto 문법은 Pandoc markdown에 기반하기 때문에 RStudio의 visual mode에서 source mode로 전환시 일부 문법이 (사전에 정의된) Pandoc markdown 문법으로 변환되며 사례는 다음과 같습니다.
    -   list `*`는 `-`로 변환
    -   `<span> </span>`는 `[]`로 변환

### Title 속성

-   Pandoc markdown에서는 텍스트에 title 속성을 추가하여 툴팁 내용을 지정할 수 있습니다.
-   This is an example of a word with a tooltip: [`hover me`]{title="This is a tooltip 1st line 1234567890 1234567890 123456780.<br> This is a 2nd line"}.
-   그러나 툴팁 내용은 text로만 인식되기 때문에 html <br> 태그가 작동하지 않습니다.



## tippy 패키지

-   tippy 패키지를 이용하면 tooltip의 text가 html 양식으로 인식되어 <br> 태그가 작동한다고 판단됩니다.
-   그러나 좌정렬이 되지 않으므로 이에 대한 tag를 추가하여야 합니다.
-   tooltip의 위치는 placement = "bottom"으로 지정하면 아래가 됩니다.
-   그러나 maxwidth 설정하는 법을 알아내지 못해 툴팁의 폭이 약 350 pixel로 제한되어 해결이 필요함.

This is a [`normal distribution`]{#normaldist}.

```{r}
#| label: tooltip
#| echo: false

library(tippy)

tippy::tippy_this(
  elementId = "normaldist", 
  tooltip = "<p align='left'>This is a tooltip 1st line 1234567890 1234567890 123456780.<br>
This is a 2nd line</p>", 
  placement = "bottom"
)
```


## Bootstrap

-   html, css, javascript를 이용한 프론트엔드 프레임워크로, 웹 페이지를 쉽게 디자인할 수 있도록 도와줍니다.

### Bootstrap tooltip

-   Bootstrap의 tooltip을 이용하면 툴팁 내용을 html 양식으로 지정할 수 있습니다.

This is an example of a word with a tooltip: [`hover me`]{.text-primary data-bs-toggle="tooltip" data-bs-html="true" title="This is a tooltip 1st line 1234567890 1234567890 123456780.<br> This is a 2nd line"}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
  // Initialize tooltips
  document.addEventListener('DOMContentLoaded', function () {
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
      return new bootstrap.Tooltip(tooltipTriggerEl);
    });
  });
</script>
<style>
  /* Tooltip text styling */
  .tooltip-text {
    color: blue;
    text-decoration: underline;
    cursor: pointer;
  }

  /* Ensure tooltip width, wrapping, and left alignment */
  .tooltip-inner {
    white-space: pre-line; /* Preserve line breaks from &#10; */
    max-width: 1200px; /* Adjust the maximum width for your tooltip */
    text-align: left; /* Align text to the left */
    word-wrap: break-word; /* Break long words if necessary */
    overflow-wrap: break-word; /* Ensure long words break */
  }
</style>

-   CDN을 이용하여 Bootstrap의 javascript를 불러오고, tooltip을 초기화하는 script를 추가되어 있습니다.
-   tooltip의 text를 스타일링하기 위한 css를 추가되어 있습니다.
-   줄바꿈, 폭길이, 좌측정렬 등이 지정되어 있습니다.


